
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// COLLECTIVE
export const RESET_COLLECTIVE = "RESET_COLLECTIVE";
export const CREATE_COLLECTIVE_SUCCESS = "CREATE_COLLECTIVE_SUCCESS";
export const DELETE_COLLECTIVE_SUCCESS = "DELETE_COLLECTIVE_SUCCESS";
export const FINDBYR_MEMBERS_COLLECTIVE_SUCCESS = "FINDBYR_MEMBERS_COLLECTIVE_SUCCESS";
export const FINDBYR_OWNER_COLLECTIVE_SUCCESS = "FINDBYR_OWNER_COLLECTIVE_SUCCESS";
export const GET_COLLECTIVE_SUCCESS = "GET_COLLECTIVE_SUCCESS";
export const LIST_COLLECTIVE_SUCCESS = "LIST_COLLECTIVE_SUCCESS";
export const UPDATE_COLLECTIVE_SUCCESS = "UPDATE_COLLECTIVE_SUCCESS";

// FILESYSTEM
export const RESET_FILESYSTEM = "RESET_FILESYSTEM";
export const CREATE_FILESYSTEM_SUCCESS = "CREATE_FILESYSTEM_SUCCESS";
export const DELETE_FILESYSTEM_SUCCESS = "DELETE_FILESYSTEM_SUCCESS";
export const FINDBYFILENAME_FILESYSTEM_SUCCESS = "FINDBYFILENAME_FILESYSTEM_SUCCESS";
export const FINDBYR_OWNER_FILESYSTEM_SUCCESS = "FINDBYR_OWNER_FILESYSTEM_SUCCESS";
export const GET_FILESYSTEM_SUCCESS = "GET_FILESYSTEM_SUCCESS";
export const GETR_OWNER_FILESYSTEM_SUCCESS = "GETR_OWNER_FILESYSTEM_SUCCESS";
export const LIST_FILESYSTEM_SUCCESS = "LIST_FILESYSTEM_SUCCESS";
export const UPDATE_FILESYSTEM_SUCCESS = "UPDATE_FILESYSTEM_SUCCESS";

// GEOCODE
export const RESET_GEOCODE = "RESET_GEOCODE";
export const CREATE_GEOCODE_SUCCESS = "CREATE_GEOCODE_SUCCESS";
export const DELETE_GEOCODE_SUCCESS = "DELETE_GEOCODE_SUCCESS";
export const FINDBYCLASS_GEOCODE_SUCCESS = "FINDBYCLASS_GEOCODE_SUCCESS";
export const FINDBYR_OWNER_GEOCODE_SUCCESS = "FINDBYR_OWNER_GEOCODE_SUCCESS";
export const GET_GEOCODE_SUCCESS = "GET_GEOCODE_SUCCESS";
export const LIST_GEOCODE_SUCCESS = "LIST_GEOCODE_SUCCESS";
export const UPDATE_GEOCODE_SUCCESS = "UPDATE_GEOCODE_SUCCESS";

// STAKEHOLDER
export const RESET_STAKEHOLDER = "RESET_STAKEHOLDER";
export const CREATE_STAKEHOLDER_SUCCESS = "CREATE_STAKEHOLDER_SUCCESS";
export const DELETE_STAKEHOLDER_SUCCESS = "DELETE_STAKEHOLDER_SUCCESS";
export const FINDBYR_AVATAR_STAKEHOLDER_SUCCESS = "FINDBYR_AVATAR_STAKEHOLDER_SUCCESS";
export const FINDBYR_COLLECTIVE_STAKEHOLDER_SUCCESS = "FINDBYR_COLLECTIVE_STAKEHOLDER_SUCCESS";
export const FINDBYR_OWNER_STAKEHOLDER_SUCCESS = "FINDBYR_OWNER_STAKEHOLDER_SUCCESS";
export const GET_STAKEHOLDER_SUCCESS = "GET_STAKEHOLDER_SUCCESS";
export const LIST_STAKEHOLDER_SUCCESS = "LIST_STAKEHOLDER_SUCCESS";
export const UPDATE_STAKEHOLDER_SUCCESS = "UPDATE_STAKEHOLDER_SUCCESS";

// TREEDATA
export const RESET_TREEDATA = "RESET_TREEDATA";
export const BINDMEMBER_NODE_TREEDATA_SUCCESS = "BINDMEMBER_NODE_TREEDATA_SUCCESS";
export const CREATE_TREEDATA_SUCCESS = "CREATE_TREEDATA_SUCCESS";
export const DELETE_TREEDATA_SUCCESS = "DELETE_TREEDATA_SUCCESS";
export const FINDBYCLASS_TREEDATA_SUCCESS = "FINDBYCLASS_TREEDATA_SUCCESS";
export const FINDBYREF_INLAW_TREEDATA_SUCCESS = "FINDBYREF_INLAW_TREEDATA_SUCCESS";
export const FINDBYS_LASTCHILD_TREEDATA_SUCCESS = "FINDBYS_LASTCHILD_TREEDATA_SUCCESS";
export const FINDBYS_PARENT_TREEDATA_SUCCESS = "FINDBYS_PARENT_TREEDATA_SUCCESS";
export const GET_TREEDATA_SUCCESS = "GET_TREEDATA_SUCCESS";
export const GETS_PARENT_TREEDATA_SUCCESS = "GETS_PARENT_TREEDATA_SUCCESS";
export const LIST_TREEDATA_SUCCESS = "LIST_TREEDATA_SUCCESS";
export const UPDATE_TREEDATA_SUCCESS = "UPDATE_TREEDATA_SUCCESS";

// USER
export const RESET_USER = "RESET_USER";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
